"""Small, practical RAG core for mixed document uploads.

Design goal: keep the code modest. Files become section-ish chunks, chunks are
ranked with TF-IDF plus numeric/table boosts, and answers are either local
evidence summaries or generated by an OpenAI-compatible provider.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import zipfile
from dataclasses import dataclass, asdict
from io import BytesIO
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

try:
    from dotenv import load_dotenv
except Exception:  # pragma: no cover
    def load_dotenv(*_: Any, **__: Any) -> bool:
        return False


EXTS = {".pdf", ".txt", ".md", ".csv", ".tsv", ".xlsx", ".xls", ".json", ".png", ".jpg", ".jpeg", ".webp"}
PROVIDERS = {"local", "openai", "grok", "gemini", "huggingface", "openrouter"}


@dataclass
class Chunk:
    source: str
    text: str
    page: int = 1
    section: str = "Document"
    kind: str = "text"
    score: float = 0.0

    @property
    def numbers(self) -> List[str]:
        return re.findall(r"[-+]?\d+(?:\.\d+)?\s?(?:%|Å|A|nm|µM|uM|mM|kDa|Da|°C|K)?", self.text)


def _bytes(path: Path, member: str | None = None) -> bytes:
    if member:
        with zipfile.ZipFile(path) as zf:
            return zf.read(member)
    return path.read_bytes()


def _members(path: Path) -> List[Tuple[str, bytes]]:
    if path.suffix.lower() == ".zip":
        with zipfile.ZipFile(path) as zf:
            return [(n, zf.read(n)) for n in zf.namelist() if Path(n).suffix.lower() in EXTS]
    if path.suffix.lower() in EXTS:
        return [(path.name, path.read_bytes())]
    raise ValueError(f"Unsupported file type: {path.suffix}")


def _decode(raw: bytes) -> str:
    for enc in ("utf-8", "utf-16", "latin-1"):
        try:
            return raw.decode(enc)
        except UnicodeDecodeError:
            pass
    return raw.decode("utf-8", errors="ignore")


def _pdf(raw: bytes, max_pages: int) -> List[Tuple[int, str]]:
    try:
        from pypdf import PdfReader

        reader = PdfReader(BytesIO(raw))
        return [(i + 1, page.extract_text() or "") for i, page in enumerate(reader.pages[:max_pages])]
    except Exception as exc:
        return [(1, f"PDF extraction failed: {exc}")]


def _table(raw: bytes, name: str) -> str:
    try:
        import pandas as pd

        ext = Path(name).suffix.lower()
        if ext in {".csv", ".tsv"}:
            return pd.read_csv(BytesIO(raw), sep="\t" if ext == ".tsv" else ",").to_markdown(index=False)
        sheets = pd.read_excel(BytesIO(raw), sheet_name=None)
        return "\n\n".join(f"Sheet: {k}\n{v.to_markdown(index=False)}" for k, v in sheets.items())
    except Exception as exc:
        return f"Table extraction failed for {name}: {exc}"


def _image(raw: bytes, name: str) -> str:
    try:
        from PIL import Image

        img = Image.open(BytesIO(raw))
        meta = f"Image {name}: {img.format}, {img.size[0]}x{img.size[1]}, mode {img.mode}."
        try:
            import pytesseract

            text = pytesseract.image_to_string(img).strip()
            return meta + ("\nOCR:\n" + text if text else "\nNo OCR text detected.")
        except Exception:
            return meta + "\nOCR not configured."
    except Exception as exc:
        return f"Image extraction failed for {name}: {exc}"


def _text(raw: bytes, name: str, max_pages: int) -> List[Tuple[int, str, str]]:
    ext = Path(name).suffix.lower()
    if ext == ".pdf":
        return [(p, t, "text") for p, t in _pdf(raw, max_pages)]
    if ext in {".csv", ".tsv", ".xlsx", ".xls"}:
        return [(1, _table(raw, name), "table")]
    if ext in {".png", ".jpg", ".jpeg", ".webp"}:
        return [(1, _image(raw, name), "image")]
    if ext == ".json":
        try:
            return [(1, json.dumps(json.loads(_decode(raw)), indent=2), "text")]
        except Exception:
            pass
    return [(1, _decode(raw), "text")]


def _section(line: str) -> bool:
    s = line.strip()
    return bool(s) and len(s) < 90 and not s.endswith(".") and (s.istitle() or s.lower() in {"abstract", "introduction", "methods", "results", "discussion"})


def _chunk(name: str, page: int, text: str, kind: str) -> List[Chunk]:
    section, buf, out = "Document", [], []

    def flush() -> None:
        nonlocal buf
        if not buf:
            return
        words = " ".join(buf).split()
        for i in range(0, len(words), 220):
            part = " ".join(words[max(0, i - 35): i + 220]).strip()
            if part:
                out.append(Chunk(name, part, page, section, kind))
        buf = []

    for line in text.splitlines():
        line = re.sub(r"\s+", " ", line).strip()
        if not line:
            continue
        if kind == "text" and _section(line):
            flush()
            section = line
        else:
            buf.append(line)
    flush()
    if not out:
        out.append(Chunk(name, text[:1200] or f"No extractable text in {name}", page, section, kind))
    return out


def build_corpus(path: Path, max_docs: int = 40, max_pages: int = 20) -> Tuple[List[Dict[str, Any]], str]:
    chunks: List[Chunk] = []
    for name, raw in _members(path)[:max_docs]:
        for page, text, kind in _text(raw, name, max_pages):
            chunks.extend(_chunk(name, page, text, kind))
    rows = [asdict(c) | {"numbers": c.numbers} for c in chunks]
    return rows, f"Indexed {len(rows)} chunks from {path.name}."


def build_corpus_from_paths(paths: List[Path], max_docs: int = 40, max_pages: int = 20) -> Tuple[List[Dict[str, Any]], str]:
    rows, notes = [], []
    for p in paths:
        part, note = build_corpus(p, max_docs, max_pages)
        rows.extend(part)
        notes.append(note)
    return rows, f"Indexed {len(rows)} chunks from {len(paths)} upload(s). " + " ".join(notes)


def retrieve(corpus: List[Dict[str, Any]], query: str, k: int = 8) -> List[Dict[str, Any]]:
    if not corpus:
        return []
    try:
        import numpy as np
        from sklearn.feature_extraction.text import TfidfVectorizer

        texts = [f"{c['source']} {c['section']} {c['kind']} {c['text']}" for c in corpus]
        mat = TfidfVectorizer(ngram_range=(1, 2), stop_words="english").fit_transform(texts + [query])
        scores = (mat[:-1] @ mat[-1].T).toarray().ravel()
        qnums = set(re.findall(r"\d+(?:\.\d+)?", query))
        for i, c in enumerate(corpus):
            scores[i] += 0.15 * len(qnums & set(re.findall(r"\d+(?:\.\d+)?", c["text"])))
            scores[i] += 0.10 if c.get("kind") == "table" and ("table" in query.lower() or qnums) else 0
        order = np.argsort(scores)[::-1][:k]
        return [dict(corpus[int(i)], score=float(scores[int(i)])) for i in order]
    except Exception:
        terms = set(re.findall(r"\w+", query.lower()))
        scored = []
        for c in corpus:
            score = len(terms & set(re.findall(r"\w+", c["text"].lower())))
            scored.append(dict(c, score=float(score)))
        return sorted(scored, key=lambda x: x["score"], reverse=True)[:k]


lexical_retrieve = retrieve
llamaindex_retrieve = retrieve
tfidf_ann_cnn_retrieve = retrieve


def format_context(chunks: List[Dict[str, Any]], max_chars: int = 9000) -> str:
    blocks = [f"[{c['source']} p.{c['page']} {c['section']} {c['kind']} score={c.get('score', 0):.3f}]\n{c['text']}" for c in chunks]
    return "\n\n".join(blocks)[:max_chars]


def _local_answer(question: str, chunks: List[Dict[str, Any]]) -> str:
    if not chunks:
        return "I could not find relevant evidence in the uploaded documents."
    bullets = [f"- `{c['source']}` p.{c['page']} ({c['section']}): {c['text'][:450]}" for c in chunks[:5]]
    return "I found this in the uploaded documents:\n\n" + "\n".join(bullets)


def _provider() -> Tuple[str, str, str, str | None]:
    p = os.getenv("LLM_PROVIDER", "local").lower()
    if p == "gemini":
        return p, os.getenv("GEMINI_MODEL", "gemini-1.5-flash"), "", os.getenv("GOOGLE_API_KEY")
    if p == "grok":
        return p, os.getenv("GROK_MODEL", "grok-2-latest"), os.getenv("GROK_BASE_URL", "https://api.x.ai/v1"), os.getenv("GROK_API_KEY")
    if p == "huggingface":
        return p, os.getenv("HF_MODEL", "meta-llama/Llama-3.1-8B-Instruct"), os.getenv("HF_BASE_URL", "https://router.huggingface.co/v1"), os.getenv("HF_TOKEN")
    if p == "openrouter":
        return p, os.getenv("OPENROUTER_MODEL", "meta-llama/llama-3.1-8b-instruct"), os.getenv("OPENROUTER_BASE_URL", "https://openrouter.ai/api/v1"), os.getenv("OPENROUTER_API_KEY")
    return p, os.getenv("OPENAI_MODEL", "gpt-4o-mini"), os.getenv("OPENAI_BASE_URL", ""), os.getenv("OPENAI_API_KEY")


def generate(question: str, chunks: List[Dict[str, Any]], external: bool = False) -> Dict[str, Any]:
    provider, model, base_url, key = _provider()
    context = format_context(chunks)
    rule = "Use only uploaded-document evidence." if not external else "Use uploaded evidence first; label any outside knowledge."
    if provider == "local" or not key:
        return {"answer": _local_answer(question, chunks), "provider": "local", "model": "evidence-only"}
    if provider == "gemini":
        try:
            import google.generativeai as genai

            genai.configure(api_key=key)
            msg = f"{rule}\n\nQuestion: {question}\n\nEvidence:\n{context}"
            out = genai.GenerativeModel(model).generate_content(msg)
            return {"answer": getattr(out, "text", "") or "", "provider": provider, "model": model}
        except Exception as exc:
            return {"answer": _local_answer(question, chunks) + f"\n\nProvider failed: {exc}", "provider": "local", "model": "fallback"}
    try:
        from openai import OpenAI

        client = OpenAI(api_key=key, base_url=base_url or None)
        msg = f"{rule}\n\nQuestion: {question}\n\nEvidence:\n{context}"
        out = client.chat.completions.create(model=model, messages=[{"role": "user", "content": msg}], temperature=0.1)
        return {"answer": out.choices[0].message.content or "", "provider": provider, "model": model}
    except Exception as exc:
        return {"answer": _local_answer(question, chunks) + f"\n\nProvider failed: {exc}", "provider": "local", "model": "fallback"}


async def answer_rag_chat(
    question: str,
    corpus: List[Dict[str, Any]],
    provider: Optional[str] = None,
    history: Optional[List[Dict[str, str]]] = None,
    top_k: int = 8,
    use_llamaindex: bool = True,
    allow_external_knowledge: bool = False,
    retrieval_engine: str = "tfidf",
) -> Dict[str, Any]:
    if provider:
        os.environ["LLM_PROVIDER"] = provider
    hits = retrieve(corpus, question, top_k)
    ans = generate(question, hits, allow_external_knowledge)
    return {"answer": ans["answer"], "sources": hits, "latency_s": 0.0, "langchain_document_count": len(hits), **ans}


async def answer_with_agent_pipeline_from_corpus(
    question: str,
    corpus: List[Dict[str, Any]],
    corpus_summary: str,
    provider: Optional[str],
    max_iterations: int = 3,
) -> Dict[str, Any]:
    if provider:
        os.environ["LLM_PROVIDER"] = provider
    turns = [
        {"agent": "planner", "message": "Break the query into retrieve, answer, verify."},
        {"agent": "executor", "message": "Retrieve evidence from uploaded documents only."},
    ]
    hits = retrieve(corpus, question, 8)
    ans = generate(question, hits)
    turns.append({"agent": "verifier", "message": "Check that the answer cites retrieved evidence.", "payload": {"sources": len(hits)}})
    return {"answer": ans["answer"], "sources": hits, "conversation": turns, "latency_s": 0.0, **ans}


async def run_multi_agent(goal: str, provider: Optional[str] = None, data_zip: Optional[Path] = None, max_docs: int = 40, max_pages: int = 20, max_iterations: int = 3) -> Dict[str, Any]:
    if not data_zip:
        raise ValueError("Provide a data path.")
    corpus, summary = build_corpus(data_zip, max_docs, max_pages)
    return await answer_with_agent_pipeline_from_corpus(goal, corpus, summary, provider, max_iterations)


def main() -> None:
    load_dotenv()
    ap = argparse.ArgumentParser()
    ap.add_argument("--data-zip", type=Path, required=True)
    ap.add_argument("--goal", default="Summarize the uploaded documents")
    ap.add_argument("--inspect-data", action="store_true")
    args = ap.parse_args()
    corpus, summary = build_corpus(args.data_zip)
    print(summary if args.inspect_data else json.dumps({"summary": summary, "answer": _local_answer(args.goal, retrieve(corpus, args.goal))}, indent=2))


if __name__ == "__main__":
    main()
